### ISSUE TITLE
unable to initialize controller..query

### ISSUE THREAD

**Issue by rmckern** [bnxm/material_floating_search_bar#11]
Hi,

Great package! One enhancement request on the controller query.

controller: controller..query = "Initial Text", throws an exception

flutter: Another exception was thrown: NoSuchMethodError: The setter 'query=' was called on null.

controller..query = "Initial Text" works in onFocusChanged.

Is there any way to show an initial query value when the query textField is first visible?

Thanks.

**Comment by bnxm** [comment]
That's because the `FloatingSearchBar` is not laid out yet and so the controller cannot delegate the call. I released a new version (0.2.0) that should take care of this and hopefully fix this.

**Comment by rmckern** [comment]
It works. Thank you.

**Comment by balasubramanian1612s** [comment]
Hey, I still face the same issue. I am setting query as 

controller..query = 'something';

I could see the text only if onFocusChanged is called.

**Comment by balasubramanian1612s** [comment]
@rmckern @bnxm

**Comment by bnxm** [comment]
The query is only shown when the search bar is open. The `title` is shown otherwise.
